__package_name__ = "pyrocco"
__version__ = "0.1.0"
__author__ = "João Palmeiro"
__author_email__ = "jm.palmeiro@campus.fct.unl.pt"
__description__ = ""
__url__ = "https://github.com/joaopalmeiro/pyrocco"
